@startuml

== configuration phase ==

participant GrubyjarPlugin
create GrubyjarProject
GrubyjarPlugin -> GrubyjarProject
create GrubyjarPrepTask
GrubyjarProject -> GrubyjarPrepTask
GrubyjarPrepTask -> Runner: doLast()
create shadowJar
GrubyjarProject -> shadowJar: shadowJar = new ShadowJar()
GrubyjarProject -> GrubyjarPrepTask: setShadowJar

GrubyjarProject -> Gem: loadGemDeps

== build phase ==

Runner -> GrubyjarPrepTask: verifyJrubyInClasspath
Runner -> GrubyjarPrepTask: createCleanWorkDir
Runner -> GrubyjarPrepTask: copyRubyMain
Runner -> GrubyjarPrepTask: configureGemDeps
GrubyjarPrepTask -> shadowJar: from(), into(), ...

Runner -> shadowJar: build

@enduml
