# This file is auto-generated by grubbyjar, but should be checked in so that
# transitive dependency changes show up in git history.

# If already running from a jar, these are no-ops as their contents are already
# on the classpath from being packed into the jar, and grubbyjar adds them to
# $LOADED_FEATURES on startup.
__requires_go_here__
