# This file is auto-generated by grubbyjar, but should be checked in so that
# transitive dependency changes show up in git history.

# If we are already running from a jar, assume these jars are on the
# classpath and don’t need explicit requires.
unless __FILE__.start_with?("uri:classloader:")
__requires_go_here__
end
