#!/bin/bash

RUBY_VERSION="$(ruby --version)"
if ! echo "$(ruby --version)" | grep -q 9.1.12.0; then
    echo "Error: expected jruby 9.1.12.0, got ${RUBY_VERSION}"
    exit 1
fi

gem install bundler
bundle install
./gradlew testall
